export const fantasyNames = {
  Humano: {
    Masculinos: ['Thom', 'Gareth', 'Edwin', 'Bjorn', 'Cormac', 'Roland', 'Leif', 'Cedric', 'Alaric', 'Baldwin', 'Duncan', 'Eadric', 'Godwin', 'Harald', 'Ivo', 'Jorvik', 'Kendrick', 'Lancelot', 'Magnus', 'Oswin', 'Percival', 'Ragnar', 'Sigurd', 'Torin', 'Ulrich', 'Wulfric', 'Alden', 'Bertram', 'Conan', 'Eldred', 'Fenric', 'Gwayne', 'Hrothgar', 'Ingram', 'Joffrey', 'Kendrick', 'Lothar', 'Maynard', 'Nigel', 'Oswald', 'Roderic', 'Saxon', 'Theobald', 'Ulfred', 'Vaughn', 'Wilfred', 'Xavier', 'York', 'Zane'],
    Femininos: ['Elena', 'Isolde', 'Eadwina', 'Astrid', 'Brigid', 'Aveline', 'Beatrice', 'Cecilia', 'Daphne', 'Eleanor', 'Freya', 'Giselle', 'Hilda', 'Ingrid', 'Joan', 'Katherine', 'Lilibet', 'Matilda', 'Nesta', 'Ophelia', 'Rowena', 'Sigrid', 'Thelma', 'Ursula', 'Vivian', 'Adelaide', 'Blanche', 'Clarissa', 'Dorothea', 'Edwina', 'Florence', 'Genevieve', 'Helena', 'Isadora', 'Juliana', 'Lorelei', 'Margery', 'Naomi', 'Olivia', 'Penelope', 'Rosalind', 'Sybil', 'Theodora', 'Viola', 'Winifred', 'Ysabel', 'Zelda'],
  },
  Elfo: {
    Masculinos: ['Aelar', 'Faelar', 'Taerith', 'Sylvaris', 'Elarion', 'Lorien', 'Thalion', 'Aerendir', 'Caladorn', 'Daereth', 'Elendir', 'Faervel', 'Galathil', 'Ilmare', 'Laeroth', 'Maethor', 'Naelar', 'Oropher', 'Quelen', 'Saereth', 'Teleri', 'Valandil', 'Arannis', 'Celeborn', 'Daelar', 'Elrond', 'Finrod', 'Gwindor', 'Haldir', 'Imladris', 'Lórien', 'Mithrandir', 'Noldor', 'Olwe', 'Peregrin', 'Quorindor', 'Sindar', 'Telperion', 'Ulmo', 'Vanyar', 'Amandil', 'Beleg', 'Cirdan', 'Ecthelion', 'Glorfindel', 'Legolas', 'Thranduil'],
    Femininos: ['Luthien', 'Naeris', 'Sylvara', 'Aeloria', 'Caleniel', 'Elaria', 'Faenara', 'Galadriel', 'Ilmareth', 'Liora', 'Miriel', 'Nienna', 'Olorin', 'Quenya', 'Saeriel', 'Telperiën', 'Valara', 'Arwen', 'Celebrian', 'Elbereth', 'Finduilas', 'Lalaith', 'Melian', 'Nerdanel', 'Olwëa', 'Perian', 'Quendë', 'Silmë', 'Tári', 'Undómiel', 'Varda', 'Aerin', 'Eärwen', 'Fëanáro', 'Idril', 'Lalwen', 'Míriel', 'Nimrodel', 'Rían', 'Tinúviel', 'Yavanna', 'Anariel', 'Celebrindal', 'Elwing', 'Lúthien', 'Tauriel'],
  },
  Anão: {
    Masculinos: ['Thrain', 'Bardra', 'Durgan', 'Helga', 'Thorin', 'Balin', 'Dwalin', 'Gloin', 'Oin', 'Bifur', 'Bofur', 'Bombur', 'Durin', 'Fili', 'Kili', 'Nori', 'Ori', 'Dori', 'Gimli', 'Bruni', 'Farin', 'Frerin', 'Gror', 'Ibun', 'Khazad', 'Lofar', 'Mardin', 'Narvi', 'Ragin', 'Sigrun', 'Torbjorn', 'Ulfar', 'Vigrim', 'Yngvar', 'Zargoth', 'Alaric', 'Borin', 'Dreng', 'Eitri', 'Fjolnir', 'Grumm', 'Hrothgar', 'Jorunn', 'Korgul', 'Lorik', 'Mogrin', 'Thorkel'],
    Femininos: ['Helga', 'Bardra', 'Disa', 'Dagna', 'Frida', 'Gerta', 'Hilda', 'Inga', 'Jorunn', 'Klara', 'Lofn', 'Magna', 'Nanna', 'Olga', 'Ragna', 'Sigrid', 'Thora', 'Ulrika', 'Vilda', 'Ylva', 'Astrid', 'Bruna', 'Dagmar', 'Eira', 'Freydis', 'Gunhild', 'Hildur', 'Ingrid', 'Jorunn', 'Kari', 'Liv', 'Margit', 'Njord', 'Ragnhild', 'Sigrun', 'Tove', 'Ulla', 'Vara', 'Yrsa', 'Zelda', 'Alva', 'Borghild', 'Dagny', 'Eydis', 'Frida', 'Gunda', 'Hannelore'],
  },
  Halfling: {
    Masculinos: ['Milo', 'Finnan', 'Pippin', 'Merry', 'Bilbo', 'Frodo', 'Samwise', 'Tobold', 'Drogo', 'Folco', 'Hamfast', 'Hobson', 'Largo', 'Madoc', 'Odo', 'Peregrin', 'Rorimac', 'Saradoc', 'Tobald', 'Wilcome', 'Bingo', 'Bungo', 'Dudo', 'Fastred', 'Fíli', 'Gaffer', 'Hal', 'Isembard', 'Lotho', 'Marmaduke', 'Nob', 'Otho', 'Paladin', 'Reginard', 'Robin', 'Sancho', 'Tolman', 'Waldo', 'Wiseman', 'Banazîr', 'Cotman', 'Doderic', 'Eldo', 'Faramir', 'Gildor', 'Holman'],
    Femininos: ['Seraphina', 'Marigold', 'Rosie', 'Pearl', 'Primula', 'Belladonna', 'Camellia', 'Daisy', 'Esmeralda', 'Flora', 'Geranium', 'Hazel', 'Ivy', 'Jasmine', 'Lavender', 'Lily', 'Marjoram', 'Myrtle', 'Pansy', 'Petunia', 'Poppy', 'Rose', 'Sage', 'Tansy', 'Violet', 'Amaryllis', 'Blossom', 'Clover', 'Daffodil', 'Fern', 'Heather', 'Holly', 'Iris', 'Lilac', 'Magnolia', 'Orchid', 'Peony', 'Primrose', 'Saffron', 'Thistle', 'Tulip', 'Zinnia', 'Buttercup', 'Dandelion', 'Freesia', 'Gladiolus'],
  },
  Orc: {
    Masculinos: ['Gor', 'Krug', 'Urza', 'Rashka', 'Grot', 'Korg', 'Zarg', 'Thruk', 'Vroth', 'Brak', 'Durg', 'Gorzod', 'Hruk', 'Kazz', 'Mogul', 'Rukthar', 'Skrag', 'Torgul', 'Urgok', 'Vark', 'Zog', 'Bruz', 'Drak', 'Gorz', 'Harg', 'Krum', 'Lug', 'Murk', 'Rarg', 'Skol', 'Thrall', 'Ugluk', 'Vorg', 'Warg', 'Xor', 'Yarg', 'Zruk', 'Bork', 'Gruk', 'Harz', 'Jorz', 'Krag', 'Lurz', 'Morg', 'Narg', 'Orz', 'Porg'],
    Femininos: ['Rashka', 'Urza', 'Grotka', 'Korgul', 'Zarga', 'Thruka', 'Brakka', 'Durgi', 'Gorzha', 'Hrukka', 'Kazza', 'Mogula', 'Ruktha', 'Skraga', 'Torgulka', 'Urgoka', 'Varka', 'Zoga', 'Bruzka', 'Drakka', 'Gorzha', 'Hargi', 'Krummi', 'Luga', 'Murka', 'Rarga', 'Skola', 'Thralla', 'Ugluka', 'Vorga', 'Warka', 'Xora', 'Yarga', 'Zrukka', 'Borkka', 'Grukka', 'Harza', 'Jorza', 'Kraga', 'Lurza', 'Morga', 'Narga', 'Orza', 'Porga'],
  },
  Tiefling: {
    Masculinos: ['Zariel', 'Azazel', 'Belial', 'Asmodeus', 'Baal', 'Charon', 'Dagon', 'Leviathan', 'Mammon', 'Mephisto', 'Naberius', 'Raum', 'Stolas', 'Valac', 'Xaphan', 'Astaroth', 'Beelzebub', 'Cain', 'Damion', 'Erebus', 'Gideon', 'Hades', 'Incubus', 'Jinn', 'Kobal', 'Lucifer', 'Malphas', 'Naamah', 'Orcus', 'Paimon', 'Qliphoth', 'Raumel', 'Samael', 'Tartarus', 'Uriel', 'Vritra', 'Xezbeth', 'Yaldabaoth', 'Zepar', 'Abaddon', 'Baphomet', 'Chemosh', 'Dantalion', 'Focalor', 'Gressil'],
    Femininos: ['Lilith', 'Nyx', 'Sable', 'Vex', 'Zyra', 'Astarte', 'Belphia', 'Carmilla', 'Drusilla', 'Echidna', 'Freyja', 'Gorgo', 'Hecate', 'Ishtar', 'Jezebel', 'Kali', 'Lamia', 'Medusa', 'Nefertari', 'Orobas', 'Persephone', 'Ravenna', 'Sekhmet', 'Tiamat', 'Ursula', 'Vespera', 'Xanthe', 'Ysmeine', 'Zafira', 'Alecto', 'Belladonna', 'Circe', 'Dabria', 'Eris', 'Furia', 'Harpy', 'Inanna', 'Jinx', 'Keres', 'Morgana', 'Nereid', 'Oizys', 'Pandora', 'Rhea', 'Selene'],
  },
  Draconato: {
    Masculinos: ['Rhazak', 'Vythari', 'Skaar', 'Ezzirith', 'Drakon', 'Khyzar', 'Zorak', 'Thryme', 'Vexor', 'Azrath', 'Brakthar', 'Corthax', 'Dravex', 'Ebonar', 'Fyrak', 'Gorzod', 'Haxion', 'Jormung', 'Kraxus', 'Lythar', 'Mordax', 'Nyrath', 'Othrax', 'Pyrak', 'Quazik', 'Ralthor', 'Ssythik', 'Tormak', 'Urgoth', 'Vyrak', 'Xyther', 'Yazir', 'Zarthax', 'Aethar', 'Balthor', 'Cryon', 'Drayce', 'Ezrath', 'Falthar', 'Grymox', 'Hyrak', 'Jorath', 'Klyther', 'Morzak', 'Nyther', 'Orvax'],
    Femininos: ['Vythari', 'Ezzirith', 'Ssyra', 'Drakona', 'Azrith', 'Brythka', 'Cerynn', 'Draycia', 'Ezmera', 'Fyrina', 'Gorzha', 'Haxina', 'Jorvyn', 'Klyra', 'Lythara', 'Myrith', 'Nyxara', 'Orythia', 'Pyrith', 'Quazira', 'Ralthia', 'Ssythia', 'Thrymeia', 'Urgotha', 'Vyrina', 'Xythra', 'Yazira', 'Zarthia', 'Aethyra', 'Balthera', 'Cryona', 'Draycia', 'Ezrithia', 'Falthera', 'Grymixa', 'Hyraxa', 'Jorynna', 'Klythera', 'Morzika', 'Nythera', 'Orvaxia'],
  },
  MeioElfo: {
    Masculinos: ['Kaelen', 'Lorien', 'Thalia', 'Eryndor', 'Calen', 'Daeron', 'Elric', 'Faerith', 'Galad', 'Haleth', 'Ildric', 'Joren', 'Kaelith', 'Lareth', 'Maelor', 'Naelor', 'Orin', 'Pheren', 'Quelin', 'Rhaegar', 'Saeth', 'Taelar', 'Ulric', 'Vaelin', 'Wyllow', 'Aerith', 'Baelor', 'Coren', 'Daelith', 'Elvar', 'Fenris', 'Gavorn', 'Haelith', 'Idris', 'Jorien', 'Koryn', 'Luthar', 'Myrdin', 'Naeth', 'Othrin', 'Paldor', 'Quorin', 'Raelith', 'Sylar', 'Taerin', 'Voryn', 'Zaelin'],
    Femininos: ['Nyra', 'Thalia', 'Aeloria', 'Calith', 'Elaria', 'Faenya', 'Galena', 'Halira', 'Ilvara', 'Jorina', 'Kaelynn', 'Lirien', 'Maelith', 'Narye', 'Oriel', 'Phaedra', 'Quenya', 'Rhaena', 'Saeril', 'Taelith', 'Vaelora', 'Wynna', 'Aerithia', 'Belith', 'Celina', 'Dariel', 'Elenya', 'Faelith', 'Gavina', 'Helyra', 'Idrina', 'Jorynna', 'Kaerith', 'Loryn', 'Myrithia', 'Naerys', 'Orithia', 'Phalyn', 'Quelith', 'Rhiannon', 'Sylvara', 'Taelynn', 'Voryna', 'Wyllith', 'Zaerys'],
  },
  Gnomo: {
    Masculinos: ['Fizzwick', 'Bimpnottin', 'Wizzle', 'Tinkla', 'Cogsworth', 'Doodle', 'Fizban', 'Gnomus', 'Jinxel', 'Klaxon', 'Mizzix', 'Nibbles', 'Poxie', 'Quixotic', 'Razzle', 'Sprocket', 'Tinker', 'Widget', 'Zephyr', 'Blinky', 'Crank', 'Dazzle', 'Elmo', 'Fidget', 'Gizmo', 'Hiccup', 'Inky', 'Jolt', 'Knick', 'Loco', 'Muddle', 'Nixie', 'Ozzy', 'Pipkin', 'Quirky', 'Ringo', 'Skiff', 'Tweak', 'Vroom', 'Whizzy', 'Yaffle', 'Zizzle', 'Boggle', 'Chuckle', 'Doodlebug', 'Flimflam', 'Giggles'],
    Femininos: ['Tinkla', 'Wizzlepop', 'Bimpette', 'Fizzina', 'Cogette', 'Doodlina', 'Fizzy', 'Gnomina', 'Jinxie', 'Klaxina', 'Mizzette', 'Nibblet', 'Poxina', 'Quixota', 'Razzlina', 'Sprocketta', 'Tinkerbell', 'Widgette', 'Zephyra', 'Blinkie', 'Cranka', 'Dazzlina', 'Elmina', 'Fidgette', 'Gizmina', 'Hiccupa', 'Inkina', 'Joltie', 'Knickie', 'Locina', 'Muddlette', 'Nixina', 'Ozmina', 'Pipkine', 'Quirkya', 'Ringette', 'Skiffie', 'Tweakie', 'Vrooma', 'Whizzie', 'Yaffla', 'Zizzla', 'Boggleta', 'Chucklina', 'Doodlebugga', 'Flimflama'],
  },
};